name: "CI"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libarchive-dev libgoocanvas-2.0-dev valac meson appstream-util xvfb
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install
        # xvfb-run -a -s "-screen 0 1600x1200x32" ninja -C build install
        dbus-run-session -- xvfb-run -a -s "-screen 0 1600x1200x32" ninja -C build test
